#password.directory: C:\Users\cuonghd\Documents\GitHub\VietIs_Springboot\api\src\main\resources\pwd
password.directory: E:\VIET_IS\ProjectGit\VietIs_Springboot\api\src\main\resources\pwd

database:
  url: jdbc:mysql://localhost:3306/test?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
#  url: jdbc:mysql:Mysql@127.0.0.1:3306/test?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
  user: root
  driver.class.name: com.mysql.cj.jdbc.Driver

# app value
token.expiration: 1